server:
  servlet:
    context-path: /team01
#  ssl:
#    key-store-password: 5509kong
#    key-store-type: PKCS12
#    key-store:  classpath:keystore.p12

spring:
  profiles:
    include : secret

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update



#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#
#  datasource:
#    driver-class-name: org.h2.Driver